version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - "linux/amd64"
        - "linux/arm64"
    platform: "${TARGETPLATFORM:-linux/arm64}"
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/idp_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    volumes:
      - ./src:/app/src
      - ./target:/app/target
      - ~/.m2:/root/.m2
    depends_on:
      - db
    networks:
      - idp-network
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  db:
    image: postgres:16-alpine
    platform: "${TARGETPLATFORM:-linux/arm64}"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=idp_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - idp-network
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  db-test:
    image: postgres:16-alpine
    platform: "${TARGETPLATFORM:-linux/arm64}"
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=idp_db_test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data_test:/var/lib/postgresql/data
    networks:
      - idp-network
    profiles:
      - test
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  app-tests:
    build:
      context: .
      dockerfile: Dockerfile
      target: test-runner
      platforms:
        - "linux/amd64"
        - "linux/arm64"
    platform: "${TARGETPLATFORM:-linux/arm64}"
    environment:
      - SPRING_PROFILES_ACTIVE=test
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-test:5432/idp_db_test
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
    volumes:
      - ./src:/app/src
      - ./target:/app/target
      - ~/.m2:/root/.m2
    depends_on:
      - db-test
    networks:
      - idp-network
    command: ["mvn", "test"]
    profiles:
      - test

volumes:
  postgres_data:
  postgres_data_test:

networks:
  idp-network:
    driver: bridge
