package com.example.idpbackend.entity;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.LocalDateTime;

@Entity
@Getter
@Setter
@Table(name = "pipelines")
public class Pipeline {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable = false, unique = true)
    private String jobName;

    @Column(nullable = false)
    private String repoUrl;

    private String jenkinsfilePath;

    @Lob
    @Column(columnDefinition = "TEXT")
    private String variables; // Store as JSON string

    @CreationTimestamp
    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @UpdateTimestamp
    @Column(nullable = false)
    private LocalDateTime updatedAt;

    // Опционально, если есть информация о пользователе
    // private String createdBy;

    private String lastBuildStatus;

    private Integer lastBuildNumber;

    private LocalDateTime lastTriggeredAt;

    // Constructors, getters, and setters will be generated by Lombok
    // We can add custom logic or methods if needed later
} 